services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    # 设置字符集utf8mb4, 表名大小写不敏感
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
      --general-log=1 
      --general-log-file=/var/log/mysql/general.log
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spring_erp
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p123456"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge
